### ISSUE TITLE
Scraper will not start

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#13]
Hello!

When I click the "equal sign" to begin the scrape after entering in the url, the scraper just stays on the url page and doesn't begin.
Thanks!

**Comment by ClasicRando** [comment]
Hi, What url are you trying?

**Comment by sbokman** [comment]
https://gis.adem.alabama.gov/arcgis/rest/services/Brownfields/FeatureServer/1
Thanks!
________________________________

**Comment by ClasicRando** [comment]
Ahhh yes, the services that are tables and contain no geometry. I can resolve that later today

**Comment by ClasicRando** [comment]
Hi Sarah,

I have resolved this with #14 and merged that to resolve your problem. Let me know if anything else comes up.

**Comment by sbokman** [comment]
Thanks Steven!
________________________________
