### ISSUE TITLE
link is not read by the rest scraper

### ISSUE THREAD

**Issue by ZacZhu0819** [ClasicRando/web_rest_scraper#15]
The following link is not read by the rest scraper: https://services.arcgis.com/SzoH1oFM2apCSkx3/ArcGIS/rest/services/DEUR/FeatureServer/0

There was no error reported and the page won't stuck, just won't return anything on the page.

**Comment by ClasicRando** [comment]
Hi Zac, that issue has been resolved here #16. The spatial reference was not where I expected it to be but I have accounted for this case and added safe guards to actions later to account for a spatial reference not found.
