### ISSUE TITLE
"Request had an error. Retrying."

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#17]
Hello!

I am having an issue scraping this file: https://gis.adem.alabama.gov/arcgis/rest/services/UST_SWAA_FieldOps/MapServer/3
The error is: "Request had an error. Retrying."

Thank you!

**Comment by ClasicRando** [comment]
Interesting, from the rest service metadata, it doesn't support geojson as a scraping type so I would need to add a JSON only variant to allow scraping. I can take a look at that later today and get back to you

**Comment by sbokman** [comment]
tysm :)
________________________________

**Comment by ClasicRando** [comment]
I added support for json queries with #18 and tested the service you provided which allowed for csv scraping. Let me know if other services provide you with issues.
