### ISSUE TITLE
No reaction from scraper with this particular url 

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#19]
When trying to scrape this url, the scraper is not reacting: https://gis.adem.alabama.gov/arcgis/rest/services/Landfills/MapServer/0

I tested this url on the other scraper (https://cartong.github.io/arcgis-rest-service-export/) and received the following error message:
Service error: Pagination is not supported.. Service description:
{
  "version": 10.9,
  "type": "Feature Layer",
  "capabilities": "Map,Query,Data",
  "supportedQueryFormats": "JSON, geoJSON",
  "maxRecordCount": 1000
}

Thank you!

**Comment by ClasicRando** [comment]
Hi, this was an error in how I handled the scraping with non paginated sources. This should be fixed now if you want to try again

**Comment by sbokman** [comment]
It works now, thank you :)
________________________________
