### ISSUE TITLE
X and Y point extraction 

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#3]
Hello, is there any way to extract the X and Y values like the previous version did?
Thank you!

**Comment by ClasicRando** [comment]
Yep, I can add it as an option for Point type geometry services to extract as 2 fields for x and y. I'll update when I have time to add this feature

**Comment by sbokman** [comment]
Thank you so much for your time on this!
________________________________

**Comment by ClasicRando** [comment]
#4 Should add that functionality as an option for point geometry services

**Comment by sbokman** [comment]
Works great, thank you!
________________________________
