### ISSUE TITLE
Loading bar for scrape is near complete, but never downloads the csv

### ISSUE THREAD

**Issue by sbokman** [ClasicRando/web_rest_scraper#8]
I am trying to scrape this REST page: https://arcgis.sd.gov/arcgis/rest/services/DENR/NR34_AirQuality_View/MapServer/0
The blue loading bar on the scraper makes it all the way to the end, indicating it is near finished, but the file never downloads.
It only happens with this particular REST url (that I know of).

Thanks!

![Capture](https://user-images.githubusercontent.com/98901534/191616407-0ace9c1e-c6a9-4b03-a620-b8f55f281fd3.PNG)

**Comment by ClasicRando** [comment]
That's a bug in the extraction of point geometry when the geometry itself is null. You can the error shown in the console output.
![Screenshot from 2022-09-21 19-16-08](https://user-images.githubusercontent.com/25016036/191626386-5d823358-d3a9-46c6-a1bf-9159aafe6b8b.png)

This can be solved with a null safe call to the point geometry parameter.
https://github.com/ClasicRando/web_rest_scraper/blob/master/index.js#L760

**Comment by ClasicRando** [comment]
This has been fixed with pull request #9
